opps/liveblogging/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import EventServerDetail
from .views import EventAdminList, EventAdminDetail, EventDetail
from .conf import settings


urlpatterns = patterns(
    '',
    url(r'^admin/liveblogging/message/(?P<slug>[\w-]+)$',
        login_required(EventAdminDetail.as_view()), name='event-admin-detail',
        kwargs={'channel__long_slug': settings.OPPS_LIVEBLOGGING_CHANNEL}),
    url(r'^admin/liveblogging/message/$',
        login_required(EventAdminList.as_view()), name='event-admin-list',
        kwargs={'channel__long_slug': settings.OPPS_LIVEBLOGGING_CHANNEL}),
)

urlpatterns += patterns(
    '',
    url(r'^{}/(?P<slug>[\w-]+)\.html$'.format(
        settings.OPPS_LIVEBLOGGING_CHANNEL),
        EventDetail.as_view(), name='event',
        kwargs={'channel__long_slug': settings.OPPS_LIVEBLOGGING_CHANNEL}),

    url(r'^{}/server/(?P<slug>[\w-]+)$'.format(
        settings.OPPS_LIVEBLOGGING_CHANNEL),
        EventServerDetail.as_view(), name='event-server',
        kwargs={'channel__long_slug': settings.OPPS_LIVEBLOGGING_CHANNEL}),
)

opps/liveblogging/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    message = forms.CharField(required=True)
    class Meta:
        model = Message
        fields = ('message',)

opps/liveblogging/templates/containers/live/detail.html
<div id="result">
  {% for m in msg %}
  <p>{{ m.message|safe }}</p>
  {% endfor %}
</div>
<script>
if (!!window.EventSource) {
  var source = new EventSource("{{ context.channel.get_absolute_url }}server/{{ context.slug }}");

  source.onopen = function () {
  }

  source.onerror = function () {
  }

  source.addEventListener('update', function(e) {
    var data = JSON.parse(e.data);
    console.log(data.id, data.msg);
  }, false);

  source.addEventListener('error', function(e) {
    if (e.readyState == EventSource.CLOSED) {
      //
    }
  }, false);

  source.onmessage = function(e) {
    var data = JSON.parse(e.data)
    if (data.event == 'message'){
      var html = document.getElementById("result").innerHTML
      document.getElementById("result").innerHTML = "<p>" + data.msg + "</p>" + html;
    }
  };
} else {
  // Result to xhr polling :(
}
</script>

opps/liveblogging/templates/containers/live/detail_admin.html
{% extends "liveblog_admin_base.html" %}
{% load admin_list i18n %}
{% load url from future %}
{% block content %}
<div id="content-main">


    <div class="g-d-24 center">

        <div id="box-images">
            
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="wall-image">
                <input id="link_image" name="link_image" class="input-block-level" type="hidden">
                <div>
                    <img id="mine-thumb" src="" />
                </div>
                <div>
                    <a href="#" id="cleanImage" class="grp-button" type="button">Remover</a>
                </div>
                <div>
                    <a href="#" id="btnAddImage" class="grp-button" type="button">Adicionar Image</a>
                </div>
            </div>
            <div>
                <input id="id_message" name="message" class="input-block-level" type="text">
                <a href="#" id="btnPost" class="grp-button" type="button">{% trans "send" %}</a>
            </div>
        </form>

        <div  id="msgs">
            {% for m in msg %}
                <p>{{ m.message|safe }}</p>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

opps/liveblogging/templates/containers/live/detail_admin_soccer.html
{% extends "liveblog_admin_base.html" %}
{% load admin_list i18n %}
{% load url from future %}

{% block extrastyle %}
{{ block.super }}
<!-- <link rel="stylesheet" type="text/css" href="/static/admin/liveblogging/goalserve.css"> -->
<link rel="stylesheet" type="text/css" href="/static/admin/liveblogging/soccer.css">
{% endblock %}

{% block extrahead %}
{{ block.super }}
<script type="text/javascript" src="/static/admin/liveblogging/soccer.js"></script>
{% endblock %}

{% block content %}
<div id="content-main">
{% with match=context.transmission.match %}

  <div class="g-d-6 left">

    <div class="w-30 pull-left">
        <img src="{{match.localteam.image_url}}" title="{{ match.localteam.g_id }}"/>
    </div>
    <div class="w-70 pull-right">
        <h1>{{match.localteam.name}}</h1>
    </div>
    <hr />

    {% for lineup in match.local_lineup %}

    <div class="w-30 pull-left">
        <img src="{{lineup.player.image_url}}" />
    </div>
    <div class="w-70 pull-right">
        <h5>{{lineup.player.name}} ({{lineup.player.number}})</h5>
        {{lineup.player.position}}
        Age:{{lineup.player.age}}

    </div>
    <div class="clearfix clear"></div>

    {% endfor %}


  </div>
  <div class="g-d-12 center">

        <div id="event-buttons">
            <a href="#" class="event-button flag--text"><i class="icon"></i></a>
            <a href="#" class="event-button flag--score"><i class="icon"></i></a>
            <a href="#" class="event-button flag--rcard"><i class="icon"></i></a>
            <a href="#" class="event-button flag--ycard"><i class="icon"></i></a>
            <a href="#" class="event-button flag--replace"><i class="icon"></i></a>
        </div>

        <small>Preview</small>
        <div id="preview-box" class="feed-list">
         <div class="preview-item row item flag--rcard">
            <div class="small-2 columns time w-20 pull-left">
                <p class="event-half">1º tempo</p>
                <h1><span class="event-minute" contenteditable="true" data-placeholder="">45</span>'</h1>
            </div>
            <div class="small-10 columns description w-80 pull-right" >
                <h5><div class="event-title w-80" contenteditable="true" data-placeholder="<em>Title</em>"><em>Title</em></div></h5>

                <p>
                    <span class="icon event-icon"></span>
                    <div class="event-text w-80" contenteditable="true" data-placeholder="<em>Text</em>"><em>Text</em></div>
                </p>
            </div>
        </div>
        </div>

      <form method="post" class="clear">

        {% csrf_token %}
        <input id="id_message" name="message" class="input-block-level" type="hidden">
        <a href="#" id="btnPost" class="grp-button" type="button">{% trans "send" %}</a>
      </form>

      <div  id="msgs" class="feed-list">
        {% for m in msg %}
        <p>{{ m.message|safe }}</p>
        {% endfor %}
      </div>

<small>{{ match.id }} / {{ match.g_static_id }}</small>
  </div>

  <div class="g-d-6 right">

    <div class="w-30 pull-left">
        <img src="{{match.visitorteam.image_url}}" title="{{ match.visitorteam.g_id }}"/>
    </div>
    <div class="w-70 pull-right">
        <h1>{{match.visitorteam.name}}</h1>
    </div>
    <hr />

    {% for lineup in match.visitor_lineup %}

    <div class="w-30 pull-left">
        <img src="{{lineup.player.image_url}}" />
    </div>
    <div class="w-70 pull-right">
        <h5>{{lineup.player.name}} ({{lineup.player.number}})</h5>
        {{lineup.player.position}}
        Age:{{lineup.player.age}}

    </div>
    <div class="clearfix clear"></div>

    {% endfor %}

  </div>

{% endwith %}
</div>
{% endblock %}

opps/liveblogging/templates/containers/live/list.html
{% extends "admin/base_site.html" %}
{% load admin_list i18n %}
{% load url from future %}

{% block title %}{% trans "Liveblogging administration" %} | {% trans 'Opps site admin' %}{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li><a href="../../">{% trans "Home" %}</a> <span class="divider">/</span></li>
    <li><a href="../">{% trans "Liveblogging" %}</a> <span class="divider">/</span></li>
    <li class="active">{% trans "Menssages" %}</li>
</ul>
<div class="page-header">
  <h3>{% trans "Liveblogging administration" %}</h3>
</div>
{% endblock %}

{% block content %}
<div id="content-main">
  <ul>
  {% for event in context %}
    <li class="span4">
      <div class="thumbnail">
        <img src="{{ MEDIA_URL }}{{ event.main_image.archive }}" />
        <div class="caption">
          <h3>{{ event.title }}</h3>
          <p>{{ event.hat }}</p>
          <p><a href="{% url 'liveblogging:event-admin-detail' event.slug %}" class="btn btn-primary">{% trans "Join" %}</a></p>
        </div>
      </div>
    </li>
  {% endfor %}
  </ul>
</div>
{% endblock %}

opps/liveblogging/templates/containers/live/list_admin.html
{% extends "admin/base_site.html" %}
{% load admin_list i18n %}
{% load url from future %}

{% block title %}{% trans "Liveblogging administration" %} | {% trans 'Opps site admin' %}{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li><a href="../../">{% trans "Home" %}</a> </li>
    <li><a href="../">{% trans "Liveblogging" %}</a></li>
    <li class="active">{% trans "Menssages" %}</li>
</ul>
{% endblock %}

{% block content %}
<div class="page-header">
  <h3>{% trans "Liveblogging administration" %}</h3>
</div>
<div id="content-main">
  <ul>
  {% for event in context %}
    <li class="span4">
      <div class="thumbnail">
        <a href="{% url 'liveblogging:event-admin-detail' event.slug %}" class="btn btn-primary">
           <img src="{{ MEDIA_URL }}{{ event.main_image.archive }}" />
        </a>
        <div class="caption">
          <h3>{{ event.title }}</h3>
          <p>{{ event.hat }}</p>
          <p><a href="{% url 'liveblogging:event-admin-detail' event.slug %}" class="btn btn-primary">{% trans "Join" %}</a></p>
        </div>
      </div>
    </li>
  {% endfor %}
  </ul>
</div>
{% endblock %}